### ISSUE TITLE
Set up library distribution

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#28] opened 2018-02-06 10:18 UTC
[UPDATED 2018-10-01]

Discussion
---
- Decide on versioning schema (eg. `0.0.0-beta-x`)
- What to do with mapbox-gl? (https://github.com/CartoDB/renderer-prototype/issues/242)
- Setup distribution / polyfills for the supported browsers ([babel-env](https://babeljs.io/docs/plugins/preset-env/))

Tasks
----
- [x] Create a npm package`@carto/cartovl`
- [x] Transpiling.
- [-] Polyfills (after discussing we are not adding polyfills for now)

We are ready to go now.

**Comment by Jesus89** [comment] 2018-02-12 17:22
Related to: https://github.com/CartoDB/renderer-prototype/issues/45

**Comment by VictorVelarde** [comment] 2018-09-18 11:35
I've made a quick review. Some notes:

#### Build system
We have a build based on **Webpack 4** with two options: `build:dev` and `build:min`
- build:dev creates 4 files:
  - `carto-vl.js` (1.1MB)
  - `e396fd0b112b6fc7099e.worker.js` (134KB)
  - `carto-vl.js.map` (1MB)
  - `e396fd0b112b6fc7099e.worker.js.map` (138KB)

- build:min creates 2 files:
  - `carto-vl.min.js` (**287KB**)
  - `8041724bec85fcf46240.worker.js` (41KB)

The code currently contains several modern features (>=ES6), such as `const`, `let`, `arrow functions`, `async/await`, `includes`, `fetch`, `export & import`...). Some of these are not fully supported by old browsers, such as IE11 (a useful tool to check those compatibilities is https://caniuse.com). 

For a broader compatibility we could apply a **babel** transpiling task.

##### Adding babel test
There are currently 3 active webpack loaders:
  * webpack-glsl-loader
  * svg-inline-loader
  * worker-loader

Adding a fourth one: 'babel-loader', with 'preset-env', results in (`build:min`):
- carto-vl.min.js (475KB vs previous 287KB)
- 8041724bec85fcf46240.worker.js (49KB vs previous 41KB)

Do we really want to transpile our library?  I'm not sure if it makes sense with our target.

**Comment by VictorVelarde** [comment] 2018-09-18 14:01
Pinging you for a quick opinion on 🔝 ... @rochoa @davidmanzanares @elenatorro @jgoizueta ?

**Comment by rafaelfernandezgis** [comment] 2018-09-19 12:13
Guys, I don't want to put more on your table but I'd like just to say, please be aware how create-react-app works in terms of transpiling since it is a classic one in React developing.
Thx a lot!

**Comment by IagoLast** [comment] 2018-09-19 12:35
Hi @VictorVelarde, which browers are you [targeting](https://babeljs.io/docs/en/babel-preset-env#targets) with babel-env ? 

Maybe with a narrow browser list we can reach a balance between supported browsers and bundle size.


Another option would be releasing 2 versions, the standard and the `compatibility`, Stencilljs does something similar.

**Comment by elenatorro** [comment] 2018-09-19 12:46
In my opinion, browser compatibility > bundle size. I am not a fan of having two versions. As @IagoLast mentions, it would be great to know which browsers and versions we want to support and test the bundle size with these settings.

**Comment by IagoLast** [comment] 2018-09-19 12:54
IMO if we include carto-vl from a CDN we should provide a bundled and polyfilled version while the version uploaded to `npm` should be raw and the bundle + compile should be the responsibility of the programmer

**Comment by elenatorro** [comment] 2018-09-19 13:00
Sorry but I do not fully agree with that, because for instance, the user must not be responsible of compiling `glsl`files.

**Comment by VictorVelarde** [comment] 2018-09-19 13:48
I agree with @IagoLast in refining our target. I'll make more tests and add the figures here. Regarding to the use of different bundles, I'll stick with just one by now, to keep it simple

**Comment by VictorVelarde** [comment] 2018-09-19 16:43
I have added babel-loader to webpack and a new build configuration, which explicits the supported browsers at package.json (`browserslist`). You can check them locally just executing `npx browserslist`.

This is the size for build:min under several configurations:

| Configuration                   | Size   | Browser upport  |
| -------------            | ------ | ----- |
| current (no transp.)     | 287 KB | ?  |
| "defaults"               | 475 KB | [check](http://browserl.ist/?q=defaults) |
| "last 1 version", "not dead", ">0.2%" | 475 KB | [check](http://browserl.ist/?q=last+1+version%2C+not+dead%2C+%3E0.2%25) |
| "last 1 version", "not dead", ">1%" | 475 KB | [check](http://browserl.ist/?q=last+1+version%2C+not+dead%2C+%3E1%25) |
| "since 2018"             | 289 KB | [check](http://browserl.ist/?q=since+2018)
| "last 2 chrome versions" | 286 KB | [check](http://browserl.ist/?q=last+2+Chrome+versions) |


So as you can see, the size mantains pretty high once we use babel-loader, unless we get really restrictive (eg. last 2 chrome versions).

My concern is that probably the 'recommended' or other common configurations include several browsers without a proper WebGL support, so maybe we should start with that restriction in mind (and not JS in a broad sense). Do you know how we could we get a more precise list for that?

**Comment by VictorVelarde** [comment] 2018-09-19 18:13
I've got better results after fighting a bit with @babel/plugin-transform-runtime.

Currently, "defaults" is **358KB**, instead of 475KB (table 🔝 has not been updated yet). In any case, I still think we could improve it by being more explicit on the WebGL side.

**Comment by VictorVelarde** [comment] 2018-09-25 09:59
It seems that the plugin-transform-runtime _"defaults to assuming that all polyfillable APIs will be provided by the user. Otherwise the corejs option needs to be specified."_ ([see ref](https://babeljs.io/docs/en/babel-plugin-transform-runtime)).

**Comment by VictorVelarde** [comment] 2018-09-25 10:05
After our meeting, we've decided to move on, so this is the current status:

- 359 KB for min.js
- just 1 bundle, transpiled with babel (preset-env)
- no fetch / no promise polyfill (for old browsers like ie11, with bad performance).
- browserlist: [compatibility](https://browserl.ist/?q=defaults%2C+not+ie+%3C12%2C+not+edge+%3C17
)

We could add some polyfills in the future, if we really need them.

**Comment by rafaelfernandezgis** [comment] 2018-10-04 11:30
I can't wait for that @VictorVelarde. Thx! We actually are in a hurry to implement the library in a production environment :rocket:

**Comment by VictorVelarde** [comment] 2018-10-04 11:47
@rafaelfernandezgis How are you going to consume the library, from npm inside your own build process or from the cdn?

**Comment by rafaelfernandezgis** [comment] 2018-10-04 12:00
npm for sure, we are using react 16.3 (create-react-app)

**Comment by VictorVelarde** [comment] 2018-10-04 12:03
Did you have any issue with the current v0.8.0 from npm with your react app?

**Comment by rafaelfernandezgis** [comment] 2018-10-04 12:19
Sí, lo que estoy obteniendo es este problema:

```uda3@rafael-uda:~/carto_vl$ yarn build
yarn run v1.9.4
$ react-scripts build
Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:
        ./node_modules/@carto/carto-vl/dist/carto-vl.js:5788
Read more here: http://bit.ly/2tRViJ9
error Command failed with exit code 1.
```

**Comment by VictorVelarde** [comment] 2018-10-04 12:27
Ok, I see.  I'm adding this here for completeness: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

It looks like it is a pretty well documented issue, caused by react-scripts < v2.0.0

**Comment by rafaelfernandezgis** [comment] 2018-10-04 12:31
Well, in this point we can definitely migrate to react-scripts v2, if it resolves the previous issue. :smiley:

**Comment by VictorVelarde** [comment] 2018-10-04 13:33
By the way, lin5788 from carto-vl.js is the first line in the library with an ES6 class declaration (`class Layer`). You can try with v2.0.0

**Comment by rafaelfernandezgis** [comment] 2018-10-04 13:47
I will in a while for sure and I'll let you know how things go. Thx!

**Comment by VictorVelarde** [comment] 2018-10-05 08:10
I'm gonna close this issue, as the new build with Babel has already been merged to master, and it will be included in the next release. Feel free to reopen it if you find any problem

**Closed by VictorVelarde** 2018-10-05 08:10 UTC
Labels: 💬 Discussion

**Comment by rafaelfernandezgis** [comment] 2018-10-05 08:31
I will try in a while for sure and I'll let you know how things go. Thx @VictorVelarde

**Comment by VictorVelarde** [comment] 2018-10-10 08:29
@rafaelfernandezgis v0.9.1 has been released, with several improvements and including babel transpilation, so you should be able to test with the old version of create-react scripts

**Comment by rafaelfernandezgis** [comment] 2018-10-10 14:55
We just migrated our project to react-script v2, then we installed carto-vl@0.9.1 and it works in both local and static deploy after running yarn build. Congrats @VictorVelarde. I'll make a bloc.k to show you the example I have been following all this time using our uDA datasets with API_KEY included.

Good staff @carto :+1:

**Comment by VictorVelarde** [comment] 2018-10-10 15:53
Great, any feedback is always welcome!

**Comment by rafaelfernandezgis** [comment] 2018-10-11 09:43
As I said, this is just a basic implementation of carto-vl@0.9.1 in React (CRA2) using an API_KEY on our datasets.

[![Edit qxjm30xwm6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qxjm30xwm6)

**Comment by VictorVelarde** [comment] 2018-10-11 11:21
Great! be sure you share an API_KEY with just limited permissions on your datasets!

**Comment by VictorVelarde** [comment] 2018-10-11 12:33
CARTO_VL_Viz
