### ISSUE TITLE
Bucket color by category 

### ISSUE THREAD

**Issue by iamwfx** [CartoDB/carto-vl#519] opened 2018-06-06 20:57 UTC
Color by categories are outputting the incorrect colors unless and extra color is added in the end. I'm assuming it's for those geoms that don't have the proper label. See below. Believe @michellemho was also experiencing the same!

This is an example (see the extra color in the end): 
`color: opacity(ramp(buckets($holc_grade_x,['A','B','C','D']),[#5fce23,#0bc0ed,#ffd419,#ff4b19,#ff4b19]),.5)`

---
Update:

PR with the use cases: https://github.com/CartoDB/carto-vl/pull/552

**Comment by davidmanzanares** [comment] 2018-06-08 13:07
Hi,

Yes, that's expected behavior. Although I agree in that it is counterintuitive.

Your guess is right, it happens because the non-mentioned categories go to an extra `others` category.

I think we could detect the case in which you are already mentioning all the categories of the property in buckets, and in that case removing the need for an extra color.

What do you think @makella ?

**Comment by michellemho** [comment] 2018-06-08 14:57
I also ran into this little color bug. I think it's counterintuitive. And the behavior _without_ passing an extra color at the end leads to some unexpected behavior. Without the extra color, the geoms are still styled, but the colors seem to be randomly assigned! See map below.

**Without extra color at end of array**
```
const subwayviz = new carto.Viz(`
color: ramp(buckets($_group,['JZ','BDFM','S','7','ACE','123','456','NQRW','L','G','SIR']),
[#996633,#FF6319,#808183,#B933AD,#2850AD,#EE352E,#00933C,#FCCC0A,#A7A9AC,#6CBE45,#053159])
width: 3
`)
```
![screen shot 2018-06-06 at 4 31 38 pm](https://user-images.githubusercontent.com/12551177/41164967-6f756baa-6b0a-11e8-994f-6aaf993a6726.png)
Incorrect mapping of colors to subway lines.

**Comment by davidmanzanares** [comment] 2018-06-08 15:16
Yes, the result is not random though, and it can be useful, for example, in the previous dataset of grades you could use `ramp(buckets($holc_grade_x,['A','B','C', 'D']),[green, red, black])` to assign colors from green to red based on the grade (setting green for `A`, a red-ish green for `B`, a green-ish red for `C`, red for `D` and black for rest (Non evaluated students? that would make sense).

For example (although the dataset is quite different and the property is categorized with a buckets) you can use the color interpolation like this: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGJ1Y2tldHMoJG51bWZsb29ycywgWzEsIDQsIDUsIDEwLCAyMCwgNDBdKSwgW2JsYWNrLCB3aGl0ZV0pXG5zdHJva2VDb2xvcjogb3BhY2l0eSh3aGl0ZSwgMC4yKSIsImYiOnsibG5nIjotNzMuOTg1MzU3MDk2MDgyMDUsImxhdCI6NDAuNzQzMDg5MzU4MTc2NDM0fSwiZyI6MTIuMjI3NTg5MTU3MTMwMzY2LCJoIjoiRGFya01hdHRlciJ9

If it's public, could you send me the dataset of the grades (off-channel)? I think it could be a great dataset to showcase this.

**Comment by michellemho** [comment] 2018-06-08 16:28
Oh, okay. I think I'm starting to understand... so the subway lines `'JZ','BDFM','S','7','ACE','123','456','NQRW','L','G','SIR'`
are being assigned to some ramp that is defined between 
`#996633`,`#FF6319`,`#808183`,`#B933AD`,`#2850AD`,`#EE352E`,`#00933C`,`#FCCC0A`,`#A7A9AC`,`#6CBE45` and that last color `#053159` isn't being used at all.

Therefore, in the picture above, those lines are not _exactly_ the hex values, but some color slightly between the hex values in the ramp.

**Comment by davidmanzanares** [comment] 2018-06-08 16:35
Yes! Exactly!

The last color was reserved for the rest of the subway lines (in this case, none).

And because of that, you have one fewer color than lines. Therefore, we use color interpolation between all of those colors to get a palette based on yours, but with one more color. :joy:

**Comment by makella** [comment] 2018-06-11 16:59
@davidmanzanares 

I see two cases when users define custom colors for categories:

The first as you mention:

> I think we could detect the case in which you are already mentioning all the categories of the property in buckets, and in that case removing the need for an extra color.

I agree that if a user knows every single category in their data that having to define an additional color for `other` can be confusing. Especially when they will expect to see those exact colors represented on their map.

So my answer here would be, yes, if every category in the data is explicitly defined and the correct number of colors have been defined, then we should not require an additional `other` color.

The second case:

A user is assigning specific colors to a subset of categories that they want to highlight on their map:
[example](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGJ1Y2tldHMoJG51bWZsb29ycywgWzEsIDQsIDVdKSwgW3B1cnBsZSwgeWVsbG93LCBncmVlbl0pXG5zdHJva2VDb2xvcjogb3BhY2l0eSh3aGl0ZSwgMCkiLCJmIjp7ImxuZyI6LTczLjk4MTUyODg4NjY3MDk2LCJsYXQiOjQwLjcyODg0NDE0NTU2ODV9LCJnIjoxMy40NDY2MDQyNzAwNDEyOTcsImgiOiJEYXJrTWF0dGVyIn0=)

In this case, knowing that they need to add an additional `other` color to see the specific colors they assigned to each category can lead to confusion and knowing that all other values are mapped to an interpolated other color is not something people will get right away. 

In this case I'm thinking of what the best way would be to help people... some ideas, 

- is it possible to have all `other` values map to a default neutral (gray) or something. This could be one step in helping people understand that if you don't define each category in your data explicitly, that 

[example](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGJ1Y2tldHMoJG51bWZsb29ycywgWzEsIDQsIDVdKSwgW3B1cnBsZSwgeWVsbG93LCBncmVlbiwgZ3JheV0pXG5zdHJva2VDb2xvcjogb3BhY2l0eSh3aGl0ZSwgMCkiLCJmIjp7ImxuZyI6LTczLjk4MTUyODg4NjY3MDk2LCJsYXQiOjQwLjcyODg0NDE0NTU2ODV9LCJnIjoxMy40NDY2MDQyNzAwNDEyOTcsImgiOiJEYXJrTWF0dGVyIn0=)

- or by default, have interpolation off for category buckets?

**Comment by elenatorro** [comment] 2018-06-13 09:11
I am going to start solving the first use case, but I would like to discuss how to address the second one as we have not come up with a solution yet.

I do not know if having a default neutral color is a good idea, because what if the user has set the same color for another value? I know it is a weird case, but It may be confusing.

What would be the effect of disabling interpolation for category buckets? Is it something we want to do? May we add something to set interpolation on/off for category buckets?

Thanks :)

**Comment by makella** [comment] 2018-06-13 14:09
@elenatorro hiii! 

I like your thinking here! You want to talk through this a little?

You have a lot of good points and I was thinking similarly about having the ability to turn interpolation off for categories. I think especially with CIE Lab we are seeing some interesting color combinations (I can show you more details about this).

**Comment by elenatorro** [comment] 2018-06-13 17:59
Hi again!

We can try to see how could we add an ON/OFF option for interpolation in this case. I have made a list of use cases and checked it with @davidmanzanares to help me understand this issue and think about possible solutions.

## Use cases

### Case 1

I have a column $category with three categories: 
`$category [category1, category2, category3]`

1. **Total** number of categories == number of colors --> **do not** interpolate
`ramp(buckets($category, [category1, category2, category3]), [color1, color2, color3])`

2. **Total** number of categories < number of colors --> ignore extra colors, **do not** interpolate.
`ramp(buckets($category, [category1, category2, category3]), [color1, color2, color3, color4])`

3. **Total** number of categories > number of colors --> interpolate
`ramp(buckets($category, [category1, category2, category3]), [color1, color2])`

### Case 2
I have a column $category with four categories: 
`$category [category1, category2, category3, category4]`

4. **Less** than total number of categories == number of colors --> 
4.1: `ramp(buckets($category, [category1, category2], [color1, color2]))`
category1 and category2 --> color1 (it is actually interpolated, but it is the same color)
rest (category3 and category4) --> color2
4.2: `ramp(buckets($category, [category1, category2, category3], [color1, color2, color3]))`
category1, category2, category3 --> interpolate  between color1 and color2
rest (category4) --> color3

5. **Less** than total number of categories < colors --> 
5.1 `ramp(buckets($category, [category1, category2], [color1, color2, color3]))`
category1 --> color1
category2 --> color2
rest (category3 and category4) --> color 3

5.2 `ramp(buckets($category, [category1, category2], [color1, color2, color3, color4]))`
category1 --> color1
category2 --> color3
rest (category3 and category4) --> color 4

6. **Less** than total number of categories > colors -->
`ramp(buckets($category, [category1, category2], [color1]))`

**Closed** 2018-07-11 14:34 UTC
Labels: expressions
