### ISSUE TITLE
Features list from viewport

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#590] opened 2018-06-20 15:00 UTC
Create a method to retrieve the list of features present in the viewport.

**Comment by danicarrion** [comment] 2018-07-05 08:35
hey, just realized the PR has been merged. Is this something we can already use?

**Comment by danicarrion** [comment] 2018-07-05 10:58
thanks!!!

**Comment by padawannn** [comment] 2018-07-05 14:30
I test it with /sources/MVT.html example and It doesn't work.
<img width="1284" alt="captura de pantalla 2018-07-05 a las 16 28 30" src="https://user-images.githubusercontent.com/7164554/42329239-8377e490-8070-11e8-966f-0a3cfce9c9e7.png">

For other types of sources works well

**Comment by rochoa** [comment] 2018-07-05 14:32
What version/revision are you using?

**Comment by jgoizueta** [comment] 2018-07-05 14:45
It's a known issue: we cannot use viewportFeatures, viewportAggregation or some interactivity features with MVTs unless they have a cartodb_id property: https://github.com/CartoDB/carto-vl/issues/652

**Comment by alasarr** [comment] 2018-07-05 14:47
Is there any possibility to tell **viewportFeatures** to return all the properties? In Mastercard we need to get around 400 properties per feature.

**Comment by padawannn** [comment] 2018-07-05 14:54
@rochoa master branch

**Comment by alasarr** [comment] 2018-07-05 14:54
@jgoizueta is a possible workaround to include a cartodb_id in the external datasource?

**Comment by jgoizueta** [comment] 2018-07-05 15:12
Hey, as I've commented in https://github.com/CartoDB/carto-vl/issues/652#issuecomment-402754718 viewport functions should work in the current master, albeit with a bug (that was already there) and that can make features duplicated in the viewport aggregations and features list (if they appear in multiple tiles).

@alasarr: right now it makes no difference if you include a cartodb_id, because of the bug we have. As soon as we fix it we'll add support for having a cartodb_id in the MVT, so adding at the external source will be the right solution to avoid duplicated features

**Comment by davidmanzanares** [comment] 2018-07-05 15:14
Hey, I just commented the problematic code on `master` since it not only produces that crash with MVT sources, but it is buggy in general (it doesn't avoid repeating duplicated features on viewport aggregations when the features are in multiple tiles due to clipping).

With these lines commented you should be able to work, even though the duplication issue is still there. We'll work on that (https://github.com/CartoDB/carto-vl/issues/588), and on being able to pass or generate ids to MVT sources (https://github.com/CartoDB/carto-vl/issues/652).

**Comment by jgoizueta** [comment] 2018-07-05 15:23
@alasarr  regarding having all the 400 properties in viewportFeatures, right now you must explicitly pass all of them to the expression (you could use the JS API, and get the properties in a list programatically => `const list = s.viewportFeatures(...list);`.

We'll [discuss later](https://github.com/CartoDB/carto-vl/pull/625#issuecomment-401767002) how to simplify this.

**Comment by padawannn** [comment] 2018-07-05 15:47
Commented this lines
`if (processedFeaturesIDs.has(dataframe.properties.cartodb_id[i])) {
                    continue;
                }`

I can use viewportFeatures function in MVT source but with 600 properties It's not posible to move or zoom map and I don't know the consequences to comment this lines.

**Comment by davidmanzanares** [comment] 2018-07-05 16:08
Yes, that's what I commented on `master`, it was supposed to fix issue #588 

We've reproduced the performance problem with many properties and `viewportFeatures` and we are working on it.

**Comment by alasarr** [comment] 2018-07-05 16:17
Hi @jgoizueta we've test it and it works, we can get the 400 properties back. However, the performance is not good:

https://gist.github.com/padawannn/f721d9ac681a63636824bf8b4ff03aa5

**Comment by padawannn** [comment] 2018-07-05 16:40
I've updated my local master branch and viewportFeatures function works with MVT source like @davidmanzanares and @jgoizueta said so we are not blocked while you solve bugs

**Comment by padawannn** [comment] 2018-07-06 10:45
In our tests everything is working perfect with the latest changes

**Comment by alasarr** [comment] 2018-07-06 18:31
Vamos!! 💪  

Thank you very much for the super fast/useful help!  

Can't be more grateful

**Comment by davidmanzanares** [comment] 2018-07-09 14:07
You're welcome!

**Closed by davidmanzanares** 2018-07-09 14:07 UTC
