### ISSUE TITLE
Image getting cut off

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1017] opened 2018-10-03 17:49 UTC
@davidmanzanares 

I know in the past, we were seeing the issue where image markers were getting cut off. I am noticing it again with a particular marker design. I can't locate the previous issue to relate (sorry)!

I'm seeing that the top of the marker is getting cut off as we can see below with the right and left corners and the off center 13.

I've tried modifying the style of the marker (removing shadows, making it smaller, taking it down to bare minimum), but nothing seems to be changing where it is getting cut.

Original marker shape:
<img width="186" alt="screen shot 2018-10-03 at 11 45 29 am" src="https://user-images.githubusercontent.com/1566273/46428702-e7a44f80-c701-11e8-8d37-e514bb75b482.png">

Rendered w/ VL:
<img width="416" alt="screen shot 2018-10-03 at 11 42 45 am" src="https://user-images.githubusercontent.com/1566273/46428550-7d8baa80-c701-11e8-81bf-00409f16d462.png">

SVG file:
[Off.svg.zip](https://github.com/CartoDB/carto-vl/files/2443125/Off.svg.zip)

cc @urbanphes

**Comment by makella** [comment] 2018-10-03 18:09
just to see, tested in Builder, seems to be ok:
<img width="812" alt="screen shot 2018-10-03 at 12 08 44 pm" src="https://user-images.githubusercontent.com/1566273/46430024-2ab3f200-c705-11e8-9afd-7f72b0bd8695.png">

**Comment by davidmanzanares** [comment] 2018-10-04 08:31
I was able to reproduce the bug, the problem is that we are not rendering a small part of the icons. Until this is solved, you can work around it by putting a bigger transparency region in the border of your assets.

**Comment by makella** [comment] 2018-10-10 16:15
closing this as we know it is a known issue and this specific use case was solved by increasing the transparent region around the marker.

**Comment by VictorVelarde** [comment] 2018-10-11 07:09
II would say that is also happening here: https://github.com/CartoDB/carto-vl/issues/1052 where it looks like the upper side of the square is being cut off

**Comment by davidmanzanares** [comment] 2018-10-17 11:42
Hey, I'm happy my workaround "works", but we shouldn't close this since this is not fixed

**Comment by davidmanzanares** [comment] 2018-10-18 12:58
No problem @makella 

@rochoa this has automatically been moved to TODO by github. Let me know if you want to prioritize it.

**Closed** 2018-10-26 15:05 UTC
Labels: 🐛Bug
