### ISSUE TITLE
Rendering artefact when zooming

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/carto-vl#111] opened 2018-02-26 08:26 UTC
I'm not sure if this is a bug but  as you can see in the following gif, the orange dot blinks at a certain zoom level. Something similar happens with the other points.

[![https://gyazo.com/95d52d9c82c90f266e07a4603051b3aa](https://i.gyazo.com/95d52d9c82c90f266e07a4603051b3aa.gif)](https://gyazo.com/95d52d9c82c90f266e07a4603051b3aa)

[Map link](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCRhbW91bnQvNTAwMCkqMjAqKHpvb20oKS80MDAwKzAuMDEpKjEuNVxuY29sb3I6IHJhbXAoJGNhdGVnb3J5LCBQcmlzbSkiLCJmIjp7ImxuZyI6Mi4xNjg1ODIwMTUwODYyNTgzLCJsYXQiOjQxLjM4ODEzMTkwNjQ0NTc4fSwiZyI6MTIuNDAxMTI4NDY4ODkyNDQ1fQ==)

**Comment by rochoa** [comment] 2018-02-28 17:32
This could be related to the fact that for different zoom levels the returned points are not in the same order. Are you forcing the ordering?

**Comment by IagoLast** [comment] 2018-03-01 07:41
nope, how do I force it?

**Comment by rochoa** [comment] 2018-03-01 11:09
You can use `order: asc(width())`, as per https://github.com/CartoDB/renderer-prototype/pull/70. See [example](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCRhbW91bnQvNTAwMCkqMjAqKHpvb20oKS80MDAwKzAuMDEpKjEuNVxuY29sb3I6IHJhbXAoJGNhdGVnb3J5LCBQcmlzbSlcbm9yZGVyOiBkZXNjKHdpZHRoKCkpIiwiZiI6eyJsbmciOjIuMTY1MTE2NDk4MjE4MzY3MywibGF0Ijo0MS4zOTMwMjE1Nzc3MTg2NTZ9LCJnIjoxNS41NDk3NDM2MDE5OTg2OTR9).

However, I'm also having a weird behaviour forcing the order.

![order-glitch](https://user-images.githubusercontent.com/45346/36841669-4dad0370-1d49-11e8-88da-6ceff3664261.gif)


cc @davidmanzanares

**Comment by davidmanzanares** [comment] 2018-03-01 11:26
This seems like a regression, the ordering functionality was tested precisely against this dataset. The implemented functionality never intended to be a perfect ordering, but this is worse than the expected behavior.

**Comment by rochoa** [comment] 2018-03-01 12:18
Thanks. 👍

**Comment by davidmanzanares** [comment] 2018-04-04 11:14
I just understood the problem, which is not trivial to solve.

The ordering works as expected, although this is an unintended consequence.

The problem is caused by the use of `zoom()`, which, of course, change at each frame when zooming in/out, that means that point width will change accordingly. Since ordering is a loose ordering based on buckets, when we have two points with widths `9.9` and `10.1` the order is defined, but when they have `10.1` and `10.2` the order is undefined (it will render the order provided by the source).

This change cause popping, and it can be easily reproduced by https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCRhbW91bnQvNTAwMCkqMjAqKDIrc2luKG5vdygpKSkqMS41XG5jb2xvcjogcmFtcCgkY2F0ZWdvcnksIFByaXNtKVxub3JkZXI6IGRlc2Mod2lkdGgoKSlcbnJlc29sdXRpb246IDEiLCJmIjp7ImxuZyI6Mi4xNjUxMjA0MTQxMTIxNTI1LCJsYXQiOjQxLjM4ODgzODc1NTA1OTc5NH0sImciOjE1LjM4MTMzMzE5NjY1OTQ4NX0=

In the meantime, I recommend to don't mix `order` with `zoom()`.

**Comment by davidmanzanares** [comment] 2018-09-03 12:34
I documented this behavior https://github.com/CartoDB/carto-vl/pull/918

I think that this should be left as `won't fix` or at least deprioritized.

cc: @rochoa

**Closed** 2018-09-03 15:56 UTC
Labels: 🐛Bug, 🔀 Expressions
