### ISSUE TITLE
"blendToViz" method is not compatible with "blendTo" method

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#892] opened 2018-08-24 13:36 UTC
Support ticket related: https://github.com/CartoDB/support/issues/1718

Other issues that _may_ be related:
* https://github.com/CartoDB/carto-vl/issues/389
* https://github.com/CartoDB/carto-vl/issues/864

## Description

Use case: we want to change the color of all the features in a visualization when the user clicks on a feature, except the feature that has been clicked. We want this feature to change to a different color.

## Code

```js
    const viz = new carto.Viz(`
      width: sqrt($pop_2015)/200
      color: opacity(yellow, 0.2)
    `);

    const updatedViz = new carto.Viz(`
      width: sqrt($pop_2015)/200
      color: opacity(red, 0.2)
    `);

    const layer = new carto.Layer('layer', mySource, viz);
    const interactivity = new carto.Interactivity(layer);
    const delay = 500;

    interactivity.on('featureClick', event => {
      if (event.features.length > 0) {
        const clickedFeature = event.features[0];
        layer
          .blendToViz(updatedViz, delay)
          .then(() => {
            clickedFeature.color.blendTo(s.namedColor('blue'), delay);
          });
      }
    });

    interactivity.on('featureClickOut', event => {
      layer.blendToViz(viz, delay)
    });
```

We must expect the clicked feature color change to 'blue' once the rest of the features have been colored to red (with opacity). As we can see in the gif below, the behaviour is unexpected.

![blendto](https://user-images.githubusercontent.com/3824953/44587287-cbcc9600-a7b2-11e8-8a3e-31e5639940c4.gif)

**Comment by davidmanzanares** [comment] 2018-08-27 15:26
I think the issue is that that's trying to use the wrong tool for the job. Being the tool `blendToViz` and the job changing feature styles and the global style with the same click.

To be clearer, the issue is that `blendToViz` replace the entire viz, while `blendTo` modifies a Viz. Trying to mix both concurrently produces a race condition, I think I saw some flags trying to prevent this, but my guess is that was broken. In any case, using `blendToViz` is a bad idea here because you don't want to modify the entire Viz
This is much more easy to solve by using `blendTo` instead of `blendToViz`.

This is the provided example fixed with that:
```
<!DOCTYPE html>
<html>

<head>
  <title>Interactive based styling | CARTO</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <!-- Include CARTO VL JS -->
  <script src="https://libs.cartocdn.com/carto-vl/v0.6.2/carto-vl.min.js"></script>
  <!-- Include Mapbox GL JS -->
  <script src="https://libs.cartocdn.com/mapbox-gl/v0.45.0-carto1/mapbox-gl.js"></script>
  <!-- Include Mapbox GL CSS -->
  <link href="https://libs.cartocdn.com/mapbox-gl/v0.45.0-carto1/mapbox-gl.css" rel="stylesheet" />
  <link href="https://carto.com/developers/carto-vl/examples/maps/style.css" rel="stylesheet">
</head>

<body>
  <div id="map"></div>
  <aside class="toolbox">
    <div class="box">
      <header>
        <h1>Interactive based styling</h1>
      </header>
      <section>
        <p class="description open-sans">Style a feature based on type of interactivity</p>
        <div class="separator"></div>
        <section class="usage">
          <header>USAGE</header>
          <p class="open-sans">Hover and click on the points</p>
        </section>
      </section>
      <footer class="js-footer"></footer>
    </div>
  </aside>
  <div id="loader">
    <div class="CDB-LoaderIcon CDB-LoaderIcon--big">
      <svg class="CDB-LoaderIcon-spinner" viewBox="0 0 50 50">
        <circle class="CDB-LoaderIcon-path" cx="25" cy="25" r="20" fill="none"></circle>
      </svg>
    </div>
  </div>
  <script>
    const map = new mapboxgl.Map({
      container: 'map',
      style: 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json',
      center: [0, 30],
      zoom: 1.5,
      scrollZoom: false,
      dragRotate: false,
      touchZoomRotate: false,
    });
    carto.setDefaultAuth({
      user: 'cartovl',
      apiKey: 'default_public'
    });

    const s = carto.expressions;
    const mySource = new carto.source.Dataset('world_population_2015');
    const viz = new carto.Viz(`
      width: sqrt($pop_2015)/200
      color: opacity(yellow, 0.2)
    `);
    const globalColor = viz.color;

    const myLayer = new carto.Layer('layer', mySource, viz);
    const interactivity = new carto.Interactivity(myLayer);
    const delay = 500;
    let clickedFeature = null;
    let clicked = false;

    interactivity.on('featureClick', event => {
        event.features.forEach(feature=>{
            feature.color.blendTo(carto.expressions.namedColor('yellow'));
            feature.strokeColor.blendTo(carto.expressions.namedColor('red'));
            globalColor.blendTo(carto.expressions.namedColor('blue'))
        });
    });

    interactivity.on('featureClickOut', event => {
        event.features.map(clickedOutFeature=>{
            clickedOutFeature.reset();
        });
    });

    myLayer.addTo(map, 'watername_ocean');
    myLayer.on('loaded', hideLoader);

    function hideLoader() {
      document.getElementById('loader').style.display = 'none';
    }
  </script>
</body>

</html>
```

Hope it helps, feel free to reopen if needed

**Closed by davidmanzanares** 2018-08-27 15:26 UTC
Labels: 🐛Bug

**Comment by stevelewis99** [comment] 2018-08-28 11:12
Hey, just wondering if this example/best practice will be placed somewhere for customer reference?
Thanks!

**Comment by rochoa** [comment] 2018-08-28 13:50
@stevelewis99, that's a really good point. It's not clear in the documentation what are the trade-offs and side-effects of using `layer.blendToViz`.

However, after discussing it offline with @davidmanzanares, we guessed that you preferred to keep using the String API, and since there is no way to change the `viz.color` property with the String API you found to use blendToViz as the only alternative without having to use the JS API.

Apart from clarifying the documentation for the `layer.blendToViz` method, we are gonna enable using the String API as described before. See https://github.com/CartoDB/carto-vl/issues/904.
