### ISSUE TITLE
Firefox: 'Error: invalid MVT date' for all timestamps

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-vl#416] opened 2018-05-15 13:27 UTC
I was previously able to do torque maps off of timestamp columns but starting on May 14, I get a `Error: invalid MVT date` in the browser console. Torque maps off of numeric columns work as expected.

The following used to work on table `all_month_3` from user `eschbacher`:
```
color: #5D69B1
width: 10
filter: torque(linear($time, time('2015-01-18T18:32:53Z'), time('2015-02-17T18:23:11Z')), 10)
```

Map: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiYWxsX21vbnRoXzMiLCJiIjoiIiwiYyI6ImVzY2hiYWNoZXIiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiAjNUQ2OUIxXG53aWR0aDogMTBcbmZpbHRlcjogdG9ycXVlKGxpbmVhcigkdGltZSwgdGltZSgnMjAxNS0wMS0xOFQxODozMjo1M1onKSwgdGltZSgnMjAxNS0wMi0xN1QxODoyMzoxMVonKSksIDEwKSIsImYiOnsibG5nIjotMjIuNDc5NDQyMDYwNzIzOTU0LCJsYXQiOi0xLjQyMTA4NTQ3MTUyMDIwMDRlLTEzfSwiZyI6MC4yNTI2NjUzMTkwODMwNjI5NCwiaCI6IkRhcmtNYXR0ZXIifQ==

**Comment by davidmanzanares** [comment] 2018-05-17 11:10
Hi @andy-esch, can you recheck? The link works fine for me

**Comment by andy-esch** [comment] 2018-05-17 13:07
Ah, it works fine on Chrome but throws the invalid MVT date error on Firefox (my default browser).

**Comment by jgoizueta** [comment] 2018-06-13 15:32
I've checked this: I can reproduce the problem (kinda) in Firefox 60.0.2 (I don't see the error message in the console but the map is broken).
Then I've verified this is fixed by #495 as expected (since date strings are not parsed anymore because dates come from the server as numbers)

**Comment by IagoLast** [comment] 2018-06-14 07:28
fixed in https://github.com/CartoDB/carto-vl/issues/130

**Comment by IagoLast** [comment] 2018-06-14 07:28
fixed in https://github.com/CartoDB/carto-vl/issues/130

**Comment by davidmanzanares** [comment] 2018-06-14 10:14
This is not fixed

**Comment by IagoLast** [comment] 2018-06-20 08:28
🤔 [this map](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiYWxsX21vbnRoXzMiLCJiIjoiIiwiYyI6ImVzY2hiYWNoZXIiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiAjNUQ2OUIxXG53aWR0aDogMTBcbmZpbHRlcjogdG9ycXVlKGxpbmVhcigkdGltZSwgdGltZSgnMjAxNS0wMS0xOFQxODozMjo1M1onKSwgdGltZSgnMjAxNS0wMi0xN1QxODoyMzoxMVonKSksIDEwKSIsImYiOnsibG5nIjotMjIuNDc5NDQyMDYwNzIzOTU0LCJsYXQiOi0xLjQyMTA4NTQ3MTUyMDIwMDRlLTEzfSwiZyI6MC4yNTI2NjUzMTkwODMwNjI5NCwiaCI6IkRhcmtNYXR0ZXIifQ==) doesnt work in firefox to me but I dont see the `invalid date`  error

**Comment by davidmanzanares** [comment] 2018-06-20 08:36
Doesn't work for me either. Maybe it's that we haven't released it to ghpages, but, in any case, it would be good to have here a link to the client-side PR that should or have fixed this.

**Comment by IagoLast** [comment] 2018-06-20 08:53
Do you mean https://github.com/CartoDB/carto-vl/pull/495 ?

**Comment by davidmanzanares** [comment] 2018-06-20 09:06
Yes, thank you

**Comment by IagoLast** [comment] 2018-06-26 09:28
now is fixed :)

**Closed by IagoLast** 2018-06-26 09:28 UTC
Labels: bug
