### ISSUE TITLE
ORDER BY in query not being respected in VL with draw order of features

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#844] opened 2018-08-15 16:36 UTC
Related to: https://github.com/CartoDB/carto-vl/issues/20

I'm noticing that when there is an ORDER BY in a query, that the features aren't drawing as expected. Is this expected behavior?

For example, in the screenshot below, each symbol is colored and sized by an attribute `avg_waiting_time` where the query orders by `avg_waiting_time desc` what I would expect to see (and what I see in Builder) is the smaller points to draw on top of the larger ones. As you can see where the central large red circles are, that isn't being respected as there are several smaller points still drawing underneath the larger ones:

<img width="908" alt="screen shot 2018-08-15 at 10 31 45 am" src="https://user-images.githubusercontent.com/1566273/44160063-71c32680-a076-11e8-888f-60f4067d752a.png">

Even if I add 
`order: width(desc)`

It still doesn't change the viz:
<img width="812" alt="screen shot 2018-08-15 at 10 33 39 am" src="https://user-images.githubusercontent.com/1566273/44160163-c4044780-a076-11e8-9a31-bfbcd42db342.png">

Just in case, the full query for the dataset (client project so can't share map in public repo):

```
SELECT CONNECTION_NAME,
       sum(occupancy) AS occupancy,
       avg(avg_waiting_time) AS avg_waiting_time,
       the_geom,
       the_geom_webmercator,
       row_number() over() AS cartodb_id,
       hour
FROM table
WHERE avg_waiting_time > 0
  AND trip_date >= '2018-07-18'
  AND trip_date < '2018-07-19'
GROUP BY CONNECTION_NAME,
         hour,
         the_geom,
         the_geom_webmercator
ORDER BY avg_waiting_time DESC
```

**Comment by davidmanzanares** [comment] 2018-08-16 16:09
I think this is expected behavior due to the way Maps API works.

cc: @Algunenano

**Comment by davidmanzanares** [comment] 2018-08-17 08:55
Ok, I saw one problem, to use CARTO VL ordering function you should use:
`order: desc(width())`
Instead of
`order: width(desc)`

An error is not thrown because https://github.com/CartoDB/carto-vl/issues/675 is not fixed.

If the issue is fixed with this, please, close the issue.

**Comment by rochoa** [comment] 2018-08-27 11:14
This should throw an error now as #675 is already fixed. Re-open if necessary.

**Closed by rochoa** 2018-08-27 11:14 UTC
Labels: 🐛Bug, 🤔 Question
